### PR TITLE
FEC-10629 Added Content CDN and Device Code for youbora config Json

### PR DESCRIPTION
**Pull request by GouravSna**

### CODE REVIEW

**Review by OrenMe — COMMENTED** [review]
Are we copying the Youbora sdk enums? If so can’t we alias them? This is not maintainable as we will need to keep tabs of their config each time we should avoid it.

**Comment by GouravSna** [comment]
> Are we copying the Youbora sdk enums? If so can’t we alias them? This is not maintainable as we will need to keep tabs of their config each time we should avoid it.

Youbora is not providing any enum. [As per the doc](https://developer.nicepeopleatwork.com/apidocs/js6/youbora.Options.html), they want us to pass [CDN Codes](http://mapi.youbora.com:8081/cdns) or [Device Codes](http://mapi.youbora.com:8081/devices)

So we picked the Json response of both and kept it in enum.

**Comment by OrenMe** [comment]
And these jsons are the ones provided by the Youbora BE APIs? If so then the app will need to keep using them via the web APIs and we will get them as strings.

**Comment by giladna** [comment]
@OrenMe 
we can provide script that generate these enums maybe if we want to be nice

**Comment by OrenMe** [comment]
As this list can be updated from time to time we shouldn't take ownership of it.
This should be indicated in our docs on how to fetch the list.

**Review by OrenMe — APPROVED** [review]

**Review by giladna — APPROVED** [review]

**Pull request merged**
